PRODUCTS = [
    ('Total Restore', 'total-restore', '1'),
    #('Total Restore', '/supplements/total-restore', '3'),  # This test fails WD-2833
    ('Total Restore', '/supplements/total-restore', '6'),
    ('Vital Reds', '/supplements/vital-reds', '1'),
    ('Vital Reds', '/supplements/vital-reds', '3'),
    ('Vital Reds', '/supplements/vital-reds', '6'),
    ('Prebiothrive', '/supplements/prebiothrive', '1'),
    ('Prebiothrive', '/supplements/prebiothrive', '3'),
    ('Prebiothrive', '/supplements/prebiothrive', '6'),
    ('Lectin Shield', '/supplements/lectin-shield', '1'),
    ('Lectin Shield', '/supplements/lectin-shield', '3'),
    ('Lectin Shield', '/supplements/lectin-shield', '6'),
    ('Primal Plants', '/supplements/primal-plants', '1'),
    ('Primal Plants', '/supplements/primal-plants', '3'),
    ('Primal Plants', '/supplements/primal-plants', '6'),
    ('Heart Defense', '/supplements/heart-defense', '1'),
    ('Heart Defense', '/supplements/heart-defense', '3'),
    ('Heart Defense', '/supplements/heart-defense', '6'),
    ('Glucose Defense', '/supplements/glucose-defense', '1'),
    #('Glucose Defense', '/supplements/glucose-defense', '3'),  # FAILS, missing zeros, has $282 not $282.00
    ('Glucose Defense', 'glucose-defense', '6'),
    ('Mediterranean Olive Leaf Extract', '/supplements/mediterranean-olive-leaf-extract', '1'),
    ('Mediterranean Olive Leaf Extract', '/supplements/mediterranean-olive-leaf-extract', '3'),
    ('Mediterranean Olive Leaf Extract', '/supplements/mediterranean-olive-leaf-extract', '6'),
    ('Enhanced Circulation', '/supplements/enhanced-circulation-formula', '1'),
    ('Enhanced Circulation', '/supplements/enhanced-circulation-formula', '3'),
    ('Enhanced Circulation', '/supplements/enhanced-circulation-formula', '6'),
    ('bcaa', '/supplements/bcaa', '1'),
    ('bcaa', '/supplements/bcaa', '3'),
    ('bcaa', '/supplements/bcaa', '6'),
    ('essential k2', '/supplements/essential-k2', '1'),
    ('essential k2', '/supplements/essential-k2', '3'),
    ('essential k2', '/supplements/essential-k2', '6'),
    ('24 Strain Probiotic', '/supplements/24-strain-probiotic', '1'),
    ('24 Strain Probiotic', '/supplements/24-strain-probiotic', '3'),
    ('24 Strain Probiotic', '/supplements/24-strain-probiotic', '6'),
    ('Red Superfruit Polyphenol', '/supplements/red-superfruit-polyphenol-blend','1'),
    ('Red Superfruit Polyphenol', '/supplements/red-superfruit-polyphenol-blend', '3'),
    ('Red Superfruit Polyphenol', '/supplements/red-superfruit-polyphenol-blend', '6'),
    ('Biomax Curcumin', '/supplements/biomax-curcumin','1'),
    ('Biomax Curcumin', '/supplements/biomax-curcumin', '3'),
    ('Biomax Curcumin', '/supplements/biomax-curcumin', '6'),
    ('Perilla Seed', '/supplements/perilla-seed-oil','1'),
    ('Perilla Seed', '/supplements/perilla-seed-oil', '3'),
    ('Perilla Seed', '/supplements/perilla-seed-oil', '6'),
    ('VITAMIN D 5000', '/supplements/vitamin-d-5000', '1'),
    ('VITAMIN D 5000', '/supplements/vitamin-d-5000', '3'),
    ('VITAMIN D 5000', '/supplements/vitamin-d-5000', '6'),
    #('Omega Advanced', '/supplements/omega-advanced', '1'),  # FAILED OUT OF STOCK
    #('Omega Advanced', '/supplements/omega-advanced', '3'),  # FAILED OUT OF STOCK
    #('Omega Advanced', '/supplements/omega-advanced', '6'),  # FAILED OUT OF STOCK
    ('Advanced Basil Formula', '/supplements/advanced-basil-formula', '1'),
    ('Advanced Basil Formula', '/supplements/advanced-basil-formula', '3'),
    ('Advanced Basil Formula', '/supplements/advanced-basil-formula', '6'),
    ('Herbal Mood Support', '/supplements/herbal-mood-support', '1'),
    ('Herbal Mood Support', '/supplements/herbal-mood-support', '3'),
    ('Herbal Mood Support', '/supplements/herbal-mood-support', '6'),
    ('Proforta', '/supplements/pro-forta-men', '1'),
    ('Proforta', '/supplements/pro-forta-men', '3'),
    ('Proforta', '/supplements/pro-forta-men', '6'),
    ('ProbioPulse', '/supplements/probiopulse', '1'),
    ('ProbioPulse', '/supplements/probiopulse', '3'),
    ('ProbioPulse', '/supplements/probiopulse', '6'),
    ('Vital Reds Travel Packs', '/supplements/vital-reds-travel-packs', '1'),
    ('Vital Reds Travel Packs', '/supplements/vital-reds-travel-packs', '3'),
    ('Vital Reds Travel Packs', '/supplements/vital-reds-travel-packs', '6'),
    ('MitoX', '/supplements/mitox', '1'),
    ('MitoX', '/supplements/mitox', '3'),
    ('MitoX', '/supplements/mitox', '6'),
    ('E-Balance', '/supplements/e-balance', '1'),
    ('E-Balance', '/supplements/e-balance', '3'),  # FAILED Price bug WD-2845
    ('E-Balance', '/supplements/e-balance', '6'),  # FAILED Price bug WD-2845
    ('ProPlant Complete Shake', '/supplements/proplant-complete-shake', '1'),
    ('ProPlant Complete Shake', '/supplements/proplant-complete-shake', '3'),
    ('ProPlant Complete Shake', '/supplements/proplant-complete-shake', '6'),
    ('Complete Liver Support', '/supplements/complete-liver-support', '1'),
    ('Complete Liver Support', '/supplements/complete-liver-support', '3'),
    ('Complete Liver Support', '/supplements/complete-liver-support', '6'),
    ('Citrus Polyphenol', '/supplements/citrus-polyphenols', '1'),
    ('Citrus Polyphenol', '/supplements/citrus-polyphenols', '3'),
    ('Citrus Polyphenol', '/supplements/citrus-polyphenols', '6'),
    ('ProbioSmile', '/supplements/probiosmile', '1'),
    ('ProbioSmile', '/supplements/probiosmile', '3'),
    ('ProbioSmile', '/supplements/probiosmile', '6'),
    ('M Vitality', '/supplements/m-vitality', '1'),
    ('M Vitality', '/supplements/m-vitality', '3'),
    ('M Vitality', '/supplements/m-vitality', '6'),
    ('Moringa Cardio Boost', '/supplements/moringa-cardio-boost', '1'),
    ('Moringa Cardio Boost', '/supplements/moringa-cardio-boost', '3'),
    ('Moringa Cardio Boost', '/supplements/moringa-cardio-boost', '6'),
    ('Correct + Calm Probiotic Treatment Cream', '/skincare/probiotic-cream', '1'),
    ('Correct + Calm Probiotic Treatment Cream', '/skincare/probiotic-cream', '2'),
    ('Correct + Calm Probiotic Treatment Cream', '/skincare/probiotic-cream', '3'),
    ('Polyphenol Reparative Serum', '/skincare/polyphenol-reparative-serum', '1'),
    ('Polyphenol Reparative Serum', '/skincare/polyphenol-reparative-serum', '2'),
    ('Polyphenol Reparative Serum', '/skincare/polyphenol-reparative-serum', '3'),
    ('Polyphenol Firm & Sculpt Cream', '/skincare/polyphenol-firm-sculpt-cream', '1'),
    ('Polyphenol Firm & Sculpt Cream', '/skincare/polyphenol-firm-sculpt-cream', '2'),
    ('Polyphenol Firm & Sculpt Cream', '/skincare/polyphenol-firm-sculpt-cream', '3'),
    ('ProbioClear', '/skincare/probioclear', '1'),
    ('ProbioClear', '/skincare/probioclear', '2'),
    ('ProbioClear', '/skincare/probioclear', '3'),
    ('Dark Spot Diminisher', '/skincare/polyphenol-dark-spot-diminisher', '1'),
    ('Dark Spot Diminisher', '/skincare/polyphenol-dark-spot-diminishe', '2'),
    ('Dark Spot Diminisher', '/skincare/polyphenol-dark-spot-diminishe', '3')
    #  Note that Food isn't included in this list, it had no price and different qty selectors
]