PRODUCTS = [
    ('Total Restore', '/product/total-restore', '1 UNIT'),
    ('Total Restore', '/product/total-restore', '3 UNITS'),
    ('Total Restore', '/product/total-restore', '6 UNITS'),
    ('Vital Reds', '/product/vital-reds', '1 UNIT'),
    ('Vital Reds', '/product/vital-reds', '3 UNITS'),
    ('Vital Reds', '/product/vital-reds', '6 UNITS'),
    ('Prebiothrive', '/product/prebiothrive', '1 UNIT'),
    ('Prebiothrive', '/product/prebiothrive', '3 UNITS'),
    ('Prebiothrive', '/product/prebiothrive', '6 UNITS'),
    ('Lectin Shield', '/product/lectin-shield', '1 UNIT'),
    ('Lectin Shield', '/product/lectin-shield', '3 UNITS'),
    ('Lectin Shield', '/product/lectin-shield', '6 UNITS'),
    ('Primal Plants', '/product/primal-plants', '1 UNIT'),
    ('Primal Plants', '/product/primal-plants', '3 UNITS'),
    ('Primal Plants', '/product/primal-plants', '6 UNITS'),
    ('Heart Defense', '/product/heart-defense', '1 UNIT'),
    ('Heart Defense', '/product/heart-defense', '3 UNITS'),
    ('Heart Defense', '/product/heart-defense', '6 UNITS'),
    ('Mediterranean Olive Leaf Extract', '/product/mediterranean-olive-leaf-extract', '1 UNIT'),
    ('Mediterranean Olive Leaf Extract', '/product/mediterranean-olive-leaf-extract', '3 UNITS'),
    ('Mediterranean Olive Leaf Extract', '/product/mediterranean-olive-leaf-extract', '6 UNITS'),
    ('Enhanced Circulation', '/product/enhanced-circulation-formula', '1 UNIT'),
    ('Enhanced Circulation', '/product/enhanced-circulation-formula', '3 UNITS'),
    ('Enhanced Circulation', '/product/enhanced-circulation-formula', '6 UNITS'),
    ('bcaa', '/product/bcaa', '1 UNIT'),
    ('bcaa', '/product/bcaa', '3 UNITS'),
    ('bcaa', '/product/bcaa', '6 UNITS'),
    ('essential k2', '/product/essential-k2', '1 UNIT'),
    ('essential k2', '/product/essential-k2', '3 UNITS'),
    ('essential k2', '/product/essential-k2', '6 UNITS'),
    ('24 Strain Probiotic', '/product/24-strain-probiotic', '1 UNIT'),
    ('24 Strain Probiotic', '/product/24-strain-probiotic', '3 UNITS'),
    ('24 Strain Probiotic', '/product/24-strain-probiotic', '6 UNITS'),
    ('Red Superfruit Polyphenol', '/product/red-superfruit-polyphenol-blend','1 UNIT'),
    ('Red Superfruit Polyphenol', '/product/red-superfruit-polyphenol-blend', '3 UNITS'),
    ('Red Superfruit Polyphenol', '/product/red-superfruit-polyphenol-blend', '6 UNITS'),
    ('Biomax Curcumin', '/product/biomax-curcumin','1 UNIT'),
    ('Biomax Curcumin', '/product/biomax-curcumin', '3 UNITS'),
    ('Biomax Curcumin', '/product/biomax-curcumin', '6 UNITS'),
    ('Perilla Seed', '/product/perilla-seed-oil','1 UNIT'),
    ('Perilla Seed', '/product/perilla-seed-oil', '3 UNITS'),
    ('Perilla Seed', '/product/perilla-seed-oil', '6 UNITS'),
    ('VITAMIN D 5000', '/product/vitamin-d-5000', '1 UNIT'),
    ('VITAMIN D 5000', '/product/vitamin-d-5000', '3 UNITS'),
    ('VITAMIN D 5000', '/product/vitamin-d-5000', '6 UNITS'),
    ('Omega Advanced', '/product/omega-advanced', '1 UNIT'),
    ('Omega Advanced', '/product/omega-advanced', '3 UNITS'),
    ('Omega Advanced', '/product/omega-advanced', '6 UNITS'),
    ('Advanced Basil Formula', '/product/advanced-basil-formula', '1 UNIT'),
    ('Advanced Basil Formula', '/product/advanced-basil-formula', '3 UNITS'),
    ('Advanced Basil Formula', '/product/advanced-basil-formula', '6 UNITS'),
    ('Herbal Mood Support', '/product/herbal-mood-support', '1 UNIT'),
    ('Herbal Mood Support', '/product/herbal-mood-support', '3 UNITS'),
    ('Herbal Mood Support', '/product/herbal-mood-support', '6 UNITS'),
    ('Pro-forta', '/product/pro-forta-men', '1 UNIT'),
    ('Pro-forta', '/product/pro-forta-men', '3 UNITS'),
    ('Pro-forta', '/product/pro-forta-men', '6 UNITS'),
    #('ProbioPulse', '/product/probiopulse', '1 UNIT'),  # Product no longer on site
    #('ProbioPulse', '/product/probiopulse', '3 UNITS'),  # Product no longer on site
    #('ProbioPulse', '/product/probiopulse', '6 UNITS'),  # Product no longer on site
    ('Vital Reds Travel Packs', '/product/vital-reds-travel-packs', '1 UNIT'),
    ('Vital Reds Travel Packs', '/product/vital-reds-travel-packs', '3 UNITS'),
    ('Vital Reds Travel Packs', '/product/vital-reds-travel-packs', '6 UNITS'),
    ('MitoX', '/product/mitox', '1 UNIT'),
    ('MitoX', '/product/mitox', '3 UNITS'),
    ('MitoX', '/product/mitox', '6 UNITS'),
    ('E-Balance', '/product/e-balance', '1 UNIT'),
    ('E-Balance', '/product/e-balance', '3 UNITS'),
    ('E-Balance', '/product/e-balance', '6 UNITS'),
    ('ProPlant Complete Shake', '/product/proplant-complete-shake', '1 UNIT'),
    ('ProPlant Complete Shake', '/product/proplant-complete-shake', '3 UNITS'),
    ('ProPlant Complete Shake', '/product/proplant-complete-shake', '6 UNITS'),
    ('Complete Liver Support', '/product/complete-liver-support', '1 UNIT'),
    ('Complete Liver Support', '/product/complete-liver-support', '3 UNITS'),
    ('Complete Liver Support', '/product/complete-liver-support', '6 UNITS'),
    ('Citrus Polyphenol', '/product/citrus-polyphenols', '1 UNIT'),
    ('Citrus Polyphenol', '/product/citrus-polyphenols', '3 UNITS'),
    ('Citrus Polyphenol', '/product/citrus-polyphenols', '6 UNITS'),
    ('ProbioSmile', '/product/probiosmile', '1 UNIT'),
    ('ProbioSmile', '/product/probiosmile', '3 UNITS'),
    ('ProbioSmile', '/product/probiosmile', '6 UNITS'),
    ('M Vitality', '/product/m-vitality', '1 UNIT'),
    ('M Vitality', '/product/m-vitality', '3 UNITS'),
    ('M Vitality', '/product/m-vitality', '6 UNITS'),
    ('Moringa Cardio Boost', '/product/moringa-cardio-boost', '1 UNIT'),
    ('Moringa Cardio Boost', '/product/moringa-cardio-boost', '3 UNITS'),
    ('Moringa Cardio Boost', '/product/moringa-cardio-boost', '6 UNITS'),
    ('Correct + Calm Probiotic Treatment', '/product/correct-calm-probiotic-treatment-cream/', '1 UNIT'),
    ('Correct + Calm Probiotic Treatment', '/product/correct-calm-probiotic-treatment-cream/', '2 UNITS'),
    ('Correct + Calm Probiotic Treatment', '/product/correct-calm-probiotic-treatment-cream/', '3 UNITS'),
    ('Polyphenol Reparative Serum', '/skincare/polyphenol-reparative-serum', '1 UNIT'),
    ('Polyphenol Reparative Serum', '/skincare/polyphenol-reparative-serum', '2 UNITS'),
    ('Polyphenol Reparative Serum', '/skincare/polyphenol-reparative-serum', '3 UNITS'),
    ('Polyphenol Firm + Sculpt Cream', '/skincare/polyphenol-firm-sculpt-cream', '1 UNIT'),
    ('Polyphenol Firm + Sculpt Cream', '/skincare/polyphenol-firm-sculpt-cream', '2 UNITS'),
    ('Polyphenol Firm + Sculpt Cream', '/skincare/polyphenol-firm-sculpt-cream', '3 UNITS'),
    ('ProbioClear', '/skincare/probioclear', '1 UNIT'),
    ('ProbioClear', '/skincare/probioclear', '2 UNITS'),
    ('ProbioClear', '/skincare/probioclear', '3 UNITS'),
    ('Dark Spot Diminisher', '/skincare/polyphenol-dark-spot-diminisher', '1 UNIT'),
    ('Dark Spot Diminisher', '/skincare/polyphenol-dark-spot-diminishe', '2 UNITS'),
    ('Dark Spot Diminisher', '/skincare/polyphenol-dark-spot-diminishe', '3 UNITS')
    # TRITRIM
]