# Product Count: 11
PRODUCTS = [
    ("BIO X4", '/products/bio-x4/', '1'),
    ('BIO X4', '/products/bio-x4/', '3'),
    ('BIO X4', '/products/bio-x4/', '6'),
    ('Carb-C6', '/products/carb-c6/', '1'),
    ('Carb-C6', '/products/carb-c6/', '3'),
    ('Carb-C6', '/products/carb-c6/', '6'),
    ('Deep Cell Activator', '/deep-cell-activator/', '1'),
    ('Deep Cell Activator', '/deep-cell-activator/', '3'),
    ('Deep Cell Activator', '/deep-cell-activator/', '6'),
    ('Krill', '/antarctic-krill-oil/', '1'),
    ('Krill', '/antarctic-krill-oil/', '3'),
    ('Krill', '/antarctic-krill-oil/', '6'),
    ('Probiotic Complex', '/products/probiotic-complex/', '1'),
    ('Probiotic Complex', '/products/probiotic-complex/', '3'),
    ('Probiotic Complex', '/products/probiotic-complex/', '6'),
    ('Move 360', '/products/move-360/', '1'),
    ('Move 360', '/products/move-360/', '2'),
    ('Move 360', '/products/move-360/', '3'),
    ('MoroSlim', '/products/moroslim/', '1'),
    ('MoroSlim', '/products/moroslim/', '3'),
    ('MoroSlim', '/products/moroslim/', '6'),
    ('PrebioBoost', '/products/prebioboost/', '1'),
    ('PrebioBoost', '/products/prebioboost/', '3'),
    ('PrebioBoost', '/products/prebioboost/', '6'),
    ('Nucific Digest', '/products/nucific-digest/', '1'),
    ('Nucific Digest', '/products/nucific-digest/', '3'),
    ('Nucific Digest', '/products/nucific-digest/', '6'),
    ('Bone Broth', '/products/bone-broth/', '1'),
    ('Bone Broth', '/products/bone-broth/', '3'),
    ('Bone Broth', '/products/bone-broth/', '6'),
    ('Advanced Slimming Probiotic', '/products/advanced-slimming-probiotic/', '1'),
    ('Advanced Slimming Probiotic', '/products/advanced-slimming-probiotic/', '3'),
    ('Advanced Slimming Probiotic', '/products/advanced-slimming-probiotic/', '6')
]