PRODUCTS = [
    #("Founder's Lash", "/shop/founders-lash-bf/ ", "1 CASE"),
    #("Founder's Lash", "/shop/founders-lash-bf/ ", "2 CASES"),
    #("Founder's Lash", "/shop/founders-lash-bf/ ", "3 CASES"),
    #("Bombshell Lash", "/shop/bombshell-lash-bf/ ", "1 CASE"),
    #("Bombshell Lash", "/shop/bombshell-lash-bf/ ", "2 CASES"),
    #("Bombshell Lash", "/shop/bombshell-lash-bf/ ", "3 CASES"),
    #("Uptown Lash", "/shop/uptown-lash-bf/", "1 CASE"),
    #("Uptown Lash", "/shop/uptown-lash-bf/", "2 CASES"),
    #("Uptown Lash", "/shop/uptown-lash-bf/", "3 CASES"),
    #("Runway Lash", "/shop/runway-lash-bf/", "1 CASE"),
    #("Runway Lash", "/shop/runway-lash-bf/", "2 CASES"),
    #("Runway Lash", "/shop/runway-lash-bf/", "3 CASES"),
    #("Allure Lash", "/shop/allure-lash-bf/", "1 CASE"),
    #("Allure Lash", "/shop/allure-lash-bf/", "2 CASES"),
    #("Allure Lash", "/shop/allure-lash-bf/", "3 CASES"),
    #("Accent Lash", "/shop/accent-lash-bf/", "1 CASE"),
    #("Accent Lash", "/shop/accent-lash-bf/", "2 CASES"),
    #("Accent Lash", "/shop/accent-lash-bf/", "3 CASES"),
    ("FOUNDER'S LASH", '/shop/founders-lash/', '1 CASE'),
    ("FOUNDER'S LASH", '/shop/founders-lash/', '2 CASES'),
    ("FOUNDER'S LASH", '/shop/founders-lash/', '3 CASES'),
    ('ALLURE LASH', '/shop/allure-lash/', '1 CASE'),
    ('ALLURE LASH', '/shop/allure-lash/', '2 CASES'),
    ('ALLURE LASH', '/shop/allure-lash/', '3 CASES'),
    ('ACCENT LASH', '/shop/accent-lash/', '1 CASE'),
    ('ACCENT LASH', '/shop/accent-lash/', '2 CASES'),
    ('ACCENT LASH', '/shop/accent-lash/', '3 CASES'),
    ('ONE TWO WASH', '/shop/one-two-wash/', '1 BOTTLE'),
    ('ONE TWO WASH', '/shop/one-two-wash/', '2 BOTTLES'),
    ('ONE TWO WASH', '/shop/one-two-wash/', '3 BOTTLES'),
    ('UPTOWN', '/shop/uptown-lash/', '1 CASE'),
    ('UPTOWN', '/shop/uptown-lash/', '2 CASES'),
    ('UPTOWN', '/shop/uptown-lash/', '3 CASES'),
    ('BOMBSHELL LASH', '/shop/bombshell-lash/', '1 CASE'),
    ('BOMBSHELL LASH', '/shop/bombshell-lash/', '2 CASES'),
    ('BOMBSHELL LASH', '/shop/bombshell-lash/', '3 CASES'),
    ('RUNWAY LASH', '/shop/runway-lash/', '1 CASE'),
    ('RUNWAY LASH', '/shop/runway-lash/', '2 CASES'),
    ('RUNWAY LASH', '/shop/runway-lash/', '3 CASES')
]